services:
  visioncraft:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    image: ghcr.io/sketchfabriq/loco
    volumes:
      - ./:/home/vscode/ros_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.Xauthority:/tmp/.Xauthority:rw
      - /dev/input:/dev/input:rw
    devices:
      - /dev/input:/dev/input:rw
    env_file:
      - .env
    entrypoint: ""
    command : sleep infinity # 
    # bash -c "source /home/vscode/interbotix_ws/devel/setup.bash && roslaunch interbotix_xslocobot_gazebo xslocobot_gazebo.launch robot_model:=locobot_wx250s show_lidar:=true use_trajectory_controllers:=true"
    # command: bash -c "source /home/vscode/interbotix_ws/devel/setup.bash &&
    #            roslaunch interbotix_xslocobot_gazebo xslocobot_gazebo.launch robot_model:=locobot_wx250s show_lidar:=true use_trajectory_controllers:=true"
    privileged: true