services:
  visioncraft:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    image: ghcr.io/sketchfabriq/locotbot:devcontainer
    volumes:
      - ./:/home/vscode/ros_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.Xauthority:/tmp/.Xauthority:rw
      - /dev/input:/dev/input:rw
    devices:
      - /dev/input:/dev/input:rw
    env_file:
      - .env
    entrypoint: ""
    command: sleep infinity
    privileged: true