name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/sketchfabriq/loco:latest
        docker build -t $IMAGE_NAME . -f .devcontainer/Dockerfile
        docker push $IMAGE_NAME 